# Generated by Django 2.1.4 on 2019-03-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistantmodel', '0001_initial'),
    ]

    
       
        
