# Generated by Django 2.1.4 on 2019-03-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistantmodel', '0002_auto_20190313_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='cour_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='group',
            name='group_courid',
            field=models.ForeignKey(on_delete='CASCADE', related_name='courseset1', to='assistantmodel.Course', to_field='cour_id'),
        ),
        migrations.AddField(
            model_name='group',
            name='group_leader',
            field=models.ForeignKey(on_delete='CASCADE', related_name='studentset0', to='assistantmodel.Student', to_field='stu_id'),
        ),
        migrations.AddField(
            model_name='group',
            name='group_member1',
            field=models.ForeignKey(on_delete='CASCADE', related_name='studentset1', to='assistantmodel.Student', to_field='stu_id'),
        ),
        migrations.AddField(
            model_name='group',
            name='group_member2',
            field=models.ForeignKey(on_delete='CASCADE', related_name='studentset2', to='assistantmodel.Student', to_field='stu_id'),
        ),
        migrations.AddField(
            model_name='group',
            name='group_member3',
            field=models.ForeignKey(on_delete='CASCADE', related_name='studentset3', to='assistantmodel.Student', to_field='stu_id'),
        ),
        migrations.AddField(
            model_name='group',
            name='group_member4',
            field=models.ForeignKey(on_delete='CASCADE', related_name='studentset4', to='assistantmodel.Student', to_field='stu_id'),
        ),
    ]
